### ISSUE TITLE
Vinted session argument

### ISSUE THREAD

**Issue by zouzoula** [Gertje823/Vinted-Scraper#9]
Hello,
I don't understand how to properly add my Vinted session after -s
With "" ou without ""?
How can I find my sessionID?
My Vinted is open on Chrome
I get "IndexError: list index out of range" line 418 & line 55

Thanks.

**Comment by Gertje823** [comment]
Just wrote a tutorial on the [wiki](https://github.com/Gertje823/Vinted-Scraper/wiki/How-to-get-Vinted-sessionID%3F). 
Hope this helps.
If you still have trouble please let me know.

**Comment by zouzoula** [comment]
Hello and thanks but still not working.
Each time I click in Vinted, each time the _vinted_fr_session value changes!

Even with " ", with ' ' ou without, I still have IndexError: list index out of range (line 418 and line 55).

I don't undertand this line in the code ;     req = s.get("https://www.vinted.nl/member/13396883-wiwi2812")
Should I paste here my own profile URL?

**Comment by Gertje823** [comment]
Found the problem. They are now behind Cloudflare. So Cloudflare was blocking any requests made by the script.
I implemented a fix. The scraper now uses the `cfscrape` module instead of `requests`  to bypass Cloudflare.
So it should be working now.

The line in the script you referring to is for obtaining the CSRF token that is later used in the requests. You can leave it as is and it should work.

**Comment by zouzoula** [comment]
Now it works great!!! Thank you so much for the help!!!
